__author__ = "Paolo Arduin"
__email__ = "paolo.arduin@errequadrosrl.com"
__license__ = "Apache Software License 2.0"
__summary__ = "SPIKE - SpaCy Pipes for Knowledge Extraction"
__title__ = "spike"
__version__ = "0.2.2-dev1"
