__author__ = "Paolo Arduin"
__email__ = "paolo.arduin@errequadrosrl.com"
__license__ = "Apache Software License 2.0"
__summary__ = "A set of custom spaCy pipeline components based on regex 🔥"
__title__ = "respacy"
__version__ = "0.1.1"
